//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCom.ThriveService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThriveService.DSCWSSoap")]
    public interface DSCWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Ping(string client, string line, bool s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateGlobalDowntimeThreshold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateGlobalDowntimeThreshold(string client, int seconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDowntimeThreshold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateDowntimeThreshold(string client, string line, int seconds);
        
        // CODEGEN: Parameter 'minutes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDowntimeDataWithString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.CreateDowntimeDataWithStringResponse CreateDowntimeDataWithString(TCom.ThriveService.CreateDowntimeDataWithStringRequest request);
        
        // CODEGEN: Parameter 'eventStart' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDowntimeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.CreateDowntimeDataResponse CreateDowntimeData(TCom.ThriveService.CreateDowntimeDataRequest request);
        
        // CODEGEN: Parameter 'minutes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTComDowntimeEvent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.CreateTComDowntimeEventResponse CreateTComDowntimeEvent(TCom.ThriveService.CreateTComDowntimeEventRequest request);
        
        // CODEGEN: Parameter 'eStart' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDowntimeEventWithTimeZone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.CreateDowntimeEventWithTimeZoneResponse CreateDowntimeEventWithTimeZone(TCom.ThriveService.CreateDowntimeEventWithTimeZoneRequest request);
        
        // CODEGEN: Parameter 'eventStart' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDowntimeDataWithTimeZone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.CreateDowntimeDataWithTimeZoneResponse CreateDowntimeDataWithTimeZone(TCom.ThriveService.CreateDowntimeDataWithTimeZoneRequest request);
        
        // CODEGEN: Parameter 'eventStart' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndCreateDowntimeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.LoginAndCreateDowntimeDataResponse LoginAndCreateDowntimeData(TCom.ThriveService.LoginAndCreateDowntimeDataRequest request);
        
        // CODEGEN: Parameter 'minutes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDowntimeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.InsertDowntimeDataResponse InsertDowntimeData(TCom.ThriveService.InsertDowntimeDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTComCaseCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CreateTComCaseCount(string eStart, string eStop, int caseCount, string line, string client);
        
        // CODEGEN: Parameter 'eventStart' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCaseCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.CreateCaseCountResponse CreateCaseCount(TCom.ThriveService.CreateCaseCountRequest request);
        
        // CODEGEN: Parameter 'eventStart' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAndCreateCaseCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TCom.ThriveService.LoginAndCreateCaseCountResponse LoginAndCreateCaseCount(TCom.ThriveService.LoginAndCreateCaseCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCaseCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertCaseCount(string str_eventStart, string str_eventStop, int caseCount, string line, string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestCaseCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetLatestCaseCount(string client, string line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestCaseCountObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        TCom.ThriveService.CaseCount GetLatestCaseCountObject(string client, string line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestDowntimeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        TCom.ThriveService.DowntimeData GetLatestDowntimeData(string client, string line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLineStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool UpdateLineStatus(string client, string line, bool on);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLineStatusWithTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool UpdateLineStatusWithTime(string client, string line, bool on, string strEventTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCollectionNode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool UpdateCollectionNode(string client, int uptime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCollectionNode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        TCom.ThriveService.DataCollectionNode GetCollectionNode(string client, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginServer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string LoginServer(string client, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDevice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool InsertDevice(TCom.ThriveService.NodeLine device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        TCom.ThriveService.NodeLine GetDevice(string client, string line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        TCom.ThriveService.NodeLine[] GetDevices(string client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestSku", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int GetLatestSku(string client, string line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string Test();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeDataWithString", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeDataWithStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string reasonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> reasonCodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string client;
        
        public CreateDowntimeDataWithStringRequest() {
        }
        
        public CreateDowntimeDataWithStringRequest(string start, string stop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            this.start = start;
            this.stop = stop;
            this.minutes = minutes;
            this.reasonCode = reasonCode;
            this.reasonCodeID = reasonCodeID;
            this.comment = comment;
            this.line = line;
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeDataWithStringResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeDataWithStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateDowntimeDataWithStringResult;
        
        public CreateDowntimeDataWithStringResponse() {
        }
        
        public CreateDowntimeDataWithStringResponse(bool CreateDowntimeDataWithStringResult) {
            this.CreateDowntimeDataWithStringResult = CreateDowntimeDataWithStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string reasonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> reasonCodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string client;
        
        public CreateDowntimeDataRequest() {
        }
        
        public CreateDowntimeDataRequest(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            this.eventStart = eventStart;
            this.eventStop = eventStop;
            this.minutes = minutes;
            this.reasonCode = reasonCode;
            this.reasonCodeID = reasonCodeID;
            this.comment = comment;
            this.line = line;
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateDowntimeDataResult;
        
        public CreateDowntimeDataResponse() {
        }
        
        public CreateDowntimeDataResponse(bool CreateDowntimeDataResult) {
            this.CreateDowntimeDataResult = CreateDowntimeDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTComDowntimeEvent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTComDowntimeEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string eStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string eStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string comment;
        
        public CreateTComDowntimeEventRequest() {
        }
        
        public CreateTComDowntimeEventRequest(string eStart, string eStop, System.Nullable<decimal> minutes, string client, string line, string comment) {
            this.eStart = eStart;
            this.eStop = eStop;
            this.minutes = minutes;
            this.client = client;
            this.line = line;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTComDowntimeEventResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTComDowntimeEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CreateTComDowntimeEventResult;
        
        public CreateTComDowntimeEventResponse() {
        }
        
        public CreateTComDowntimeEventResponse(int CreateTComDowntimeEventResult) {
            this.CreateTComDowntimeEventResult = CreateTComDowntimeEventResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeEventWithTimeZone", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeEventWithTimeZoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strTimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string reasonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> reasonCodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string client;
        
        public CreateDowntimeEventWithTimeZoneRequest() {
        }
        
        public CreateDowntimeEventWithTimeZoneRequest(System.Nullable<System.DateTime> eStart, System.Nullable<System.DateTime> eStop, string strTimeZone, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            this.eStart = eStart;
            this.eStop = eStop;
            this.strTimeZone = strTimeZone;
            this.minutes = minutes;
            this.reasonCode = reasonCode;
            this.reasonCodeID = reasonCodeID;
            this.comment = comment;
            this.line = line;
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeEventWithTimeZoneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeEventWithTimeZoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CreateDowntimeEventWithTimeZoneResult;
        
        public CreateDowntimeEventWithTimeZoneResponse() {
        }
        
        public CreateDowntimeEventWithTimeZoneResponse(int CreateDowntimeEventWithTimeZoneResult) {
            this.CreateDowntimeEventWithTimeZoneResult = CreateDowntimeEventWithTimeZoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeDataWithTimeZone", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeDataWithTimeZoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strTimeZone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string reasonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> reasonCodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string client;
        
        public CreateDowntimeDataWithTimeZoneRequest() {
        }
        
        public CreateDowntimeDataWithTimeZoneRequest(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, string strTimeZone, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            this.eventStart = eventStart;
            this.eventStop = eventStop;
            this.strTimeZone = strTimeZone;
            this.minutes = minutes;
            this.reasonCode = reasonCode;
            this.reasonCodeID = reasonCodeID;
            this.comment = comment;
            this.line = line;
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDowntimeDataWithTimeZoneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDowntimeDataWithTimeZoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateDowntimeDataWithTimeZoneResult;
        
        public CreateDowntimeDataWithTimeZoneResponse() {
        }
        
        public CreateDowntimeDataWithTimeZoneResponse(bool CreateDowntimeDataWithTimeZoneResult) {
            this.CreateDowntimeDataWithTimeZoneResult = CreateDowntimeDataWithTimeZoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAndCreateDowntimeData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginAndCreateDowntimeDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string reasonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> reasonCodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string password;
        
        public LoginAndCreateDowntimeDataRequest() {
        }
        
        public LoginAndCreateDowntimeDataRequest(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client, string password) {
            this.eventStart = eventStart;
            this.eventStop = eventStop;
            this.minutes = minutes;
            this.reasonCode = reasonCode;
            this.reasonCodeID = reasonCodeID;
            this.comment = comment;
            this.line = line;
            this.client = client;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAndCreateDowntimeDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginAndCreateDowntimeDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LoginAndCreateDowntimeDataResult;
        
        public LoginAndCreateDowntimeDataResponse() {
        }
        
        public LoginAndCreateDowntimeDataResponse(bool LoginAndCreateDowntimeDataResult) {
            this.LoginAndCreateDowntimeDataResult = LoginAndCreateDowntimeDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDowntimeData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDowntimeDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime eventStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime eventStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> minutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string reasonCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> reasonCodeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string comment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string str_eventStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string str_eventStop;
        
        public InsertDowntimeDataRequest() {
        }
        
        public InsertDowntimeDataRequest(System.DateTime eventStart, System.DateTime eventStop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client, string str_eventStart, string str_eventStop) {
            this.eventStart = eventStart;
            this.eventStop = eventStop;
            this.minutes = minutes;
            this.reasonCode = reasonCode;
            this.reasonCodeID = reasonCodeID;
            this.comment = comment;
            this.line = line;
            this.client = client;
            this.str_eventStart = str_eventStart;
            this.str_eventStop = str_eventStop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDowntimeDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertDowntimeDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InsertDowntimeDataResult;
        
        public InsertDowntimeDataResponse() {
        }
        
        public InsertDowntimeDataResponse(bool InsertDowntimeDataResult) {
            this.InsertDowntimeDataResult = InsertDowntimeDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCaseCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateCaseCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int caseCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string client;
        
        public CreateCaseCountRequest() {
        }
        
        public CreateCaseCountRequest(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, int caseCount, string line, string client) {
            this.eventStart = eventStart;
            this.eventStop = eventStop;
            this.caseCount = caseCount;
            this.line = line;
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCaseCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateCaseCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateCaseCountResult;
        
        public CreateCaseCountResponse() {
        }
        
        public CreateCaseCountResponse(bool CreateCaseCountResult) {
            this.CreateCaseCountResult = CreateCaseCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAndCreateCaseCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginAndCreateCaseCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventStop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int caseCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string line;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string password;
        
        public LoginAndCreateCaseCountRequest() {
        }
        
        public LoginAndCreateCaseCountRequest(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, int caseCount, string line, string client, string password) {
            this.eventStart = eventStart;
            this.eventStop = eventStop;
            this.caseCount = caseCount;
            this.line = line;
            this.client = client;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAndCreateCaseCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginAndCreateCaseCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LoginAndCreateCaseCountResult;
        
        public LoginAndCreateCaseCountResponse() {
        }
        
        public LoginAndCreateCaseCountResponse(bool LoginAndCreateCaseCountResult) {
            this.LoginAndCreateCaseCountResult = LoginAndCreateCaseCountResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CaseCount : EntityObject {
        
        private int idField;
        
        private System.Nullable<System.DateTime> eventStartField;
        
        private System.Nullable<System.DateTime> eventStopField;
        
        private int caseCount1Field;
        
        private string lineField;
        
        private string clientField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> EventStart {
            get {
                return this.eventStartField;
            }
            set {
                this.eventStartField = value;
                this.RaisePropertyChanged("EventStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> EventStop {
            get {
                return this.eventStopField;
            }
            set {
                this.eventStopField = value;
                this.RaisePropertyChanged("EventStop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CaseCount1 {
            get {
                return this.caseCount1Field;
            }
            set {
                this.caseCount1Field = value;
                this.RaisePropertyChanged("CaseCount1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataCollectionNode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DowntimeData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseCount))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NodeLine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int deviceSetupIdField;
        
        private string serverNameField;
        
        private string clientField;
        
        private string lineField;
        
        private int downtimeThresholdField;
        
        private int uptimeThresholdField;
        
        private string iPAddressField;
        
        private int trackingTypeField;
        
        private int addressTypeField;
        
        private string tagNameField;
        
        private int tagTypeField;
        
        private int dataTypeField;
        
        private bool trackDowntimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DeviceSetupId {
            get {
                return this.deviceSetupIdField;
            }
            set {
                this.deviceSetupIdField = value;
                this.RaisePropertyChanged("DeviceSetupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
                this.RaisePropertyChanged("ServerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int DowntimeThreshold {
            get {
                return this.downtimeThresholdField;
            }
            set {
                this.downtimeThresholdField = value;
                this.RaisePropertyChanged("DowntimeThreshold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UptimeThreshold {
            get {
                return this.uptimeThresholdField;
            }
            set {
                this.uptimeThresholdField = value;
                this.RaisePropertyChanged("UptimeThreshold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
                this.RaisePropertyChanged("IPAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TrackingType {
            get {
                return this.trackingTypeField;
            }
            set {
                this.trackingTypeField = value;
                this.RaisePropertyChanged("TrackingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
                this.RaisePropertyChanged("AddressType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TagName {
            get {
                return this.tagNameField;
            }
            set {
                this.tagNameField = value;
                this.RaisePropertyChanged("TagName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int TagType {
            get {
                return this.tagTypeField;
            }
            set {
                this.tagTypeField = value;
                this.RaisePropertyChanged("TagType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool TrackDowntime {
            get {
                return this.trackDowntimeField;
            }
            set {
                this.trackDowntimeField = value;
                this.RaisePropertyChanged("TrackDowntime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataCollectionNode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DowntimeData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CaseCount))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataCollectionNode : EntityObject {
        
        private int idField;
        
        private string serverNameField;
        
        private string clientField;
        
        private string passwordField;
        
        private string timeZoneField;
        
        private bool monitorField;
        
        private int uptimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
                this.RaisePropertyChanged("ServerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("TimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Monitor {
            get {
                return this.monitorField;
            }
            set {
                this.monitorField = value;
                this.RaisePropertyChanged("Monitor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Uptime {
            get {
                return this.uptimeField;
            }
            set {
                this.uptimeField = value;
                this.RaisePropertyChanged("Uptime");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DowntimeData : EntityObject {
        
        private int idField;
        
        private System.Nullable<System.DateTime> eventStartField;
        
        private System.Nullable<System.DateTime> eventStopField;
        
        private System.Nullable<decimal> minutesField;
        
        private string reasonCodeField;
        
        private System.Nullable<int> reasonCodeIDField;
        
        private string commentField;
        
        private string lineField;
        
        private string clientField;
        
        private System.Nullable<bool> isCreatedByAcromagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> EventStart {
            get {
                return this.eventStartField;
            }
            set {
                this.eventStartField = value;
                this.RaisePropertyChanged("EventStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> EventStop {
            get {
                return this.eventStopField;
            }
            set {
                this.eventStopField = value;
                this.RaisePropertyChanged("EventStop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
                this.RaisePropertyChanged("Minutes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
                this.RaisePropertyChanged("ReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> ReasonCodeID {
            get {
                return this.reasonCodeIDField;
            }
            set {
                this.reasonCodeIDField = value;
                this.RaisePropertyChanged("ReasonCodeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
                this.RaisePropertyChanged("Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> IsCreatedByAcromag {
            get {
                return this.isCreatedByAcromagField;
            }
            set {
                this.isCreatedByAcromagField = value;
                this.RaisePropertyChanged("IsCreatedByAcromag");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DSCWSSoapChannel : TCom.ThriveService.DSCWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DSCWSSoapClient : System.ServiceModel.ClientBase<TCom.ThriveService.DSCWSSoap>, TCom.ThriveService.DSCWSSoap {
        
        public DSCWSSoapClient() {
        }
        
        public DSCWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DSCWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSCWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DSCWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping(string client, string line, bool s) {
            return base.Channel.Ping(client, line, s);
        }
        
        public int UpdateGlobalDowntimeThreshold(string client, int seconds) {
            return base.Channel.UpdateGlobalDowntimeThreshold(client, seconds);
        }
        
        public int UpdateDowntimeThreshold(string client, string line, int seconds) {
            return base.Channel.UpdateDowntimeThreshold(client, line, seconds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.CreateDowntimeDataWithStringResponse TCom.ThriveService.DSCWSSoap.CreateDowntimeDataWithString(TCom.ThriveService.CreateDowntimeDataWithStringRequest request) {
            return base.Channel.CreateDowntimeDataWithString(request);
        }
        
        public bool CreateDowntimeDataWithString(string start, string stop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            TCom.ThriveService.CreateDowntimeDataWithStringRequest inValue = new TCom.ThriveService.CreateDowntimeDataWithStringRequest();
            inValue.start = start;
            inValue.stop = stop;
            inValue.minutes = minutes;
            inValue.reasonCode = reasonCode;
            inValue.reasonCodeID = reasonCodeID;
            inValue.comment = comment;
            inValue.line = line;
            inValue.client = client;
            TCom.ThriveService.CreateDowntimeDataWithStringResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).CreateDowntimeDataWithString(inValue);
            return retVal.CreateDowntimeDataWithStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.CreateDowntimeDataResponse TCom.ThriveService.DSCWSSoap.CreateDowntimeData(TCom.ThriveService.CreateDowntimeDataRequest request) {
            return base.Channel.CreateDowntimeData(request);
        }
        
        public bool CreateDowntimeData(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            TCom.ThriveService.CreateDowntimeDataRequest inValue = new TCom.ThriveService.CreateDowntimeDataRequest();
            inValue.eventStart = eventStart;
            inValue.eventStop = eventStop;
            inValue.minutes = minutes;
            inValue.reasonCode = reasonCode;
            inValue.reasonCodeID = reasonCodeID;
            inValue.comment = comment;
            inValue.line = line;
            inValue.client = client;
            TCom.ThriveService.CreateDowntimeDataResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).CreateDowntimeData(inValue);
            return retVal.CreateDowntimeDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.CreateTComDowntimeEventResponse TCom.ThriveService.DSCWSSoap.CreateTComDowntimeEvent(TCom.ThriveService.CreateTComDowntimeEventRequest request) {
            return base.Channel.CreateTComDowntimeEvent(request);
        }
        
        public int CreateTComDowntimeEvent(string eStart, string eStop, System.Nullable<decimal> minutes, string client, string line, string comment) {
            TCom.ThriveService.CreateTComDowntimeEventRequest inValue = new TCom.ThriveService.CreateTComDowntimeEventRequest();
            inValue.eStart = eStart;
            inValue.eStop = eStop;
            inValue.minutes = minutes;
            inValue.client = client;
            inValue.line = line;
            inValue.comment = comment;
            TCom.ThriveService.CreateTComDowntimeEventResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).CreateTComDowntimeEvent(inValue);
            return retVal.CreateTComDowntimeEventResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.CreateDowntimeEventWithTimeZoneResponse TCom.ThriveService.DSCWSSoap.CreateDowntimeEventWithTimeZone(TCom.ThriveService.CreateDowntimeEventWithTimeZoneRequest request) {
            return base.Channel.CreateDowntimeEventWithTimeZone(request);
        }
        
        public int CreateDowntimeEventWithTimeZone(System.Nullable<System.DateTime> eStart, System.Nullable<System.DateTime> eStop, string strTimeZone, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            TCom.ThriveService.CreateDowntimeEventWithTimeZoneRequest inValue = new TCom.ThriveService.CreateDowntimeEventWithTimeZoneRequest();
            inValue.eStart = eStart;
            inValue.eStop = eStop;
            inValue.strTimeZone = strTimeZone;
            inValue.minutes = minutes;
            inValue.reasonCode = reasonCode;
            inValue.reasonCodeID = reasonCodeID;
            inValue.comment = comment;
            inValue.line = line;
            inValue.client = client;
            TCom.ThriveService.CreateDowntimeEventWithTimeZoneResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).CreateDowntimeEventWithTimeZone(inValue);
            return retVal.CreateDowntimeEventWithTimeZoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.CreateDowntimeDataWithTimeZoneResponse TCom.ThriveService.DSCWSSoap.CreateDowntimeDataWithTimeZone(TCom.ThriveService.CreateDowntimeDataWithTimeZoneRequest request) {
            return base.Channel.CreateDowntimeDataWithTimeZone(request);
        }
        
        public bool CreateDowntimeDataWithTimeZone(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, string strTimeZone, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client) {
            TCom.ThriveService.CreateDowntimeDataWithTimeZoneRequest inValue = new TCom.ThriveService.CreateDowntimeDataWithTimeZoneRequest();
            inValue.eventStart = eventStart;
            inValue.eventStop = eventStop;
            inValue.strTimeZone = strTimeZone;
            inValue.minutes = minutes;
            inValue.reasonCode = reasonCode;
            inValue.reasonCodeID = reasonCodeID;
            inValue.comment = comment;
            inValue.line = line;
            inValue.client = client;
            TCom.ThriveService.CreateDowntimeDataWithTimeZoneResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).CreateDowntimeDataWithTimeZone(inValue);
            return retVal.CreateDowntimeDataWithTimeZoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.LoginAndCreateDowntimeDataResponse TCom.ThriveService.DSCWSSoap.LoginAndCreateDowntimeData(TCom.ThriveService.LoginAndCreateDowntimeDataRequest request) {
            return base.Channel.LoginAndCreateDowntimeData(request);
        }
        
        public bool LoginAndCreateDowntimeData(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client, string password) {
            TCom.ThriveService.LoginAndCreateDowntimeDataRequest inValue = new TCom.ThriveService.LoginAndCreateDowntimeDataRequest();
            inValue.eventStart = eventStart;
            inValue.eventStop = eventStop;
            inValue.minutes = minutes;
            inValue.reasonCode = reasonCode;
            inValue.reasonCodeID = reasonCodeID;
            inValue.comment = comment;
            inValue.line = line;
            inValue.client = client;
            inValue.password = password;
            TCom.ThriveService.LoginAndCreateDowntimeDataResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).LoginAndCreateDowntimeData(inValue);
            return retVal.LoginAndCreateDowntimeDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.InsertDowntimeDataResponse TCom.ThriveService.DSCWSSoap.InsertDowntimeData(TCom.ThriveService.InsertDowntimeDataRequest request) {
            return base.Channel.InsertDowntimeData(request);
        }
        
        public bool InsertDowntimeData(System.DateTime eventStart, System.DateTime eventStop, System.Nullable<decimal> minutes, string reasonCode, System.Nullable<int> reasonCodeID, string comment, string line, string client, string str_eventStart, string str_eventStop) {
            TCom.ThriveService.InsertDowntimeDataRequest inValue = new TCom.ThriveService.InsertDowntimeDataRequest();
            inValue.eventStart = eventStart;
            inValue.eventStop = eventStop;
            inValue.minutes = minutes;
            inValue.reasonCode = reasonCode;
            inValue.reasonCodeID = reasonCodeID;
            inValue.comment = comment;
            inValue.line = line;
            inValue.client = client;
            inValue.str_eventStart = str_eventStart;
            inValue.str_eventStop = str_eventStop;
            TCom.ThriveService.InsertDowntimeDataResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).InsertDowntimeData(inValue);
            return retVal.InsertDowntimeDataResult;
        }
        
        public int CreateTComCaseCount(string eStart, string eStop, int caseCount, string line, string client) {
            return base.Channel.CreateTComCaseCount(eStart, eStop, caseCount, line, client);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.CreateCaseCountResponse TCom.ThriveService.DSCWSSoap.CreateCaseCount(TCom.ThriveService.CreateCaseCountRequest request) {
            return base.Channel.CreateCaseCount(request);
        }
        
        public bool CreateCaseCount(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, int caseCount, string line, string client) {
            TCom.ThriveService.CreateCaseCountRequest inValue = new TCom.ThriveService.CreateCaseCountRequest();
            inValue.eventStart = eventStart;
            inValue.eventStop = eventStop;
            inValue.caseCount = caseCount;
            inValue.line = line;
            inValue.client = client;
            TCom.ThriveService.CreateCaseCountResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).CreateCaseCount(inValue);
            return retVal.CreateCaseCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCom.ThriveService.LoginAndCreateCaseCountResponse TCom.ThriveService.DSCWSSoap.LoginAndCreateCaseCount(TCom.ThriveService.LoginAndCreateCaseCountRequest request) {
            return base.Channel.LoginAndCreateCaseCount(request);
        }
        
        public bool LoginAndCreateCaseCount(System.Nullable<System.DateTime> eventStart, System.Nullable<System.DateTime> eventStop, int caseCount, string line, string client, string password) {
            TCom.ThriveService.LoginAndCreateCaseCountRequest inValue = new TCom.ThriveService.LoginAndCreateCaseCountRequest();
            inValue.eventStart = eventStart;
            inValue.eventStop = eventStop;
            inValue.caseCount = caseCount;
            inValue.line = line;
            inValue.client = client;
            inValue.password = password;
            TCom.ThriveService.LoginAndCreateCaseCountResponse retVal = ((TCom.ThriveService.DSCWSSoap)(this)).LoginAndCreateCaseCount(inValue);
            return retVal.LoginAndCreateCaseCountResult;
        }
        
        public bool InsertCaseCount(string str_eventStart, string str_eventStop, int caseCount, string line, string client) {
            return base.Channel.InsertCaseCount(str_eventStart, str_eventStop, caseCount, line, client);
        }
        
        public int GetLatestCaseCount(string client, string line) {
            return base.Channel.GetLatestCaseCount(client, line);
        }
        
        public TCom.ThriveService.CaseCount GetLatestCaseCountObject(string client, string line) {
            return base.Channel.GetLatestCaseCountObject(client, line);
        }
        
        public TCom.ThriveService.DowntimeData GetLatestDowntimeData(string client, string line) {
            return base.Channel.GetLatestDowntimeData(client, line);
        }
        
        public bool UpdateLineStatus(string client, string line, bool on) {
            return base.Channel.UpdateLineStatus(client, line, on);
        }
        
        public bool UpdateLineStatusWithTime(string client, string line, bool on, string strEventTime) {
            return base.Channel.UpdateLineStatusWithTime(client, line, on, strEventTime);
        }
        
        public bool UpdateCollectionNode(string client, int uptime) {
            return base.Channel.UpdateCollectionNode(client, uptime);
        }
        
        public TCom.ThriveService.DataCollectionNode GetCollectionNode(string client, string password) {
            return base.Channel.GetCollectionNode(client, password);
        }
        
        public string LoginServer(string client, string password) {
            return base.Channel.LoginServer(client, password);
        }
        
        public bool InsertDevice(TCom.ThriveService.NodeLine device) {
            return base.Channel.InsertDevice(device);
        }
        
        public TCom.ThriveService.NodeLine GetDevice(string client, string line) {
            return base.Channel.GetDevice(client, line);
        }
        
        public TCom.ThriveService.NodeLine[] GetDevices(string client) {
            return base.Channel.GetDevices(client);
        }
        
        public int GetLatestSku(string client, string line) {
            return base.Channel.GetLatestSku(client, line);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
    }
}
